apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f jupyter.yaml convert -c
    kompose.service.type: nodeport
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: jupyter
  type: NodePort
status:
  loadBalancer: {}
